version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgresql
    environment:
      - "POSTGRES_DB=exlex"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
      - "PGDATA=/var/lib/postgresql/data/exlex"
    ports:
      - "55432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:

