package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"net/mail"

	"github.com/artemmarkaryan/exlex-backend/graph/model"
)

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, email string, debug bool) (ok model.Ok, err error) {
	if _, err = mail.ParseAddress(email); err != nil {
		return
	}

	err = r.ServiceContainer.Authentication().RequestOTP(ctx, email, debug)
	ok.Ok = err == nil
	return
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string) (token model.Token, err error) {
	if _, err = mail.ParseAddress(email); err != nil {
		return
	}

	t, err := r.ServiceContainer.Authentication().VerifyOTP(ctx, email, otp)
	if err != nil {
		return
	}

	token.Access = t
	return
}

// Live is the resolver for the live field.
func (r *queryResolver) Live(ctx context.Context) (bool, error) {
	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
