// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ok struct {
	Ok bool `json:"ok"`
}

type Tokens struct {
	Access  string `json:"access"`
	Refresh string `json:"refresh"`
}
