name: deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./"
          EXCLUDE: "/.github/, /.git/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/root/exlex-api"
          SCRIPT_BEFORE: "rm -rf /root/exlex-api && mkdir /root/exlex-api"
          SCRIPT_AFTER: "cd /root/exlex-api && /usr/bin/go build -o ./bin/main ./cmd/main.go && systemctl restart exlex-api"

