name: deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: go build
        run: mkdir bin && \
          go build -o ./export/bin/main ./cmd/main.go && \
          cp -r ./migration ./export/migration

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "export/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "exlex-api"

      - name: migrate & restart process
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            goose up &&
            goose status && 
            systemctl restart exlex-api
